### ISSUE TITLE
Fix all api calls in frontend to use localhost instead of deployed render links.

### ISSUE THREAD

**Issue by nirogappnith** [nirogappnith/nirog#1] opened 2024-03-13 19:42 UTC
The backend is simultaneously deployed to a free Render account, therefore the API requests are horribly slow. For the sake of optimisation and a smooth development experience, running the backend on localhost and using those api routes is recommended. 

Go through the fronted and update all API Calls to use localhost (port 8008)

Feel free to ask in case of any doubts.

**Comment by sivakumarmanoharan** [comment] 2024-03-14 18:04
Hi Nirog, can this issue assigned to me? I will work on this

**Comment by sivakumarmanoharan** [comment] 2024-03-14 18:40
Greetings to the owner of Nirog app,

I am not getting connected to the MongoDB server with the URL provided. I am getting MongooseServerSelectionError on connecting the server in MongoDBCompass as well as with the app. Could you please give the correct credentials to work on it?
![image](https://github.com/nirogappnith/nirog/assets/42244366/caf0c73d-72bc-4310-91d1-72fd4c6a63dd)

**Comment by mehulambastha** [comment] 2024-03-16 11:26
> Hi Nirog, can this issue assigned to me? I will work on this

Hi sivakumar, yes sure you can work on the figma design. I'll assign you to the task.

**Comment by mehulambastha** [comment] 2024-03-16 11:27
> Greetings to the owner of Nirog app,
> 
> I am not getting connected to the MongoDB server with the URL provided. I am getting MongooseServerSelectionError on connecting the server in MongoDBCompass as well as with the app. Could you please give the correct credentials to work on it? ![image](https://private-user-images.githubusercontent.com/42244366/312959115-caf0c73d-72bc-4310-91d1-72fd4c6a63dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1ODg0OTQsIm5iZiI6MTcxMDU4ODE5NCwicGF0aCI6Ii80MjI0NDM2Ni8zMTI5NTkxMTUtY2FmMGM3M2QtNzJiYy00MzEwLTkxZDEtNzJmZDRjNmE2M2RkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDExMjMxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwN2IwNjc0ZTQ1YTkwZmU5MjM2MzNkY2M5MTUzYjQyZjUxN2Q3OWNjYmJmNWRkYjNjMWI1MGZjZTdhY2VmMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fpSq3aFV_DUIdI-7odzi3QIBIS_WTmEn1Ptj_3IdjYQ)

I've changed the Network Access now , please check and tell me if it works now.

**Closed as completed** 2024-03-16 11:27 UTC
Labels: good first issue

**Comment by mehulambastha** [comment] 2024-03-17 19:24
> > Hi Nirog, can this issue assigned to me? I will work on this
> 
> Hi sivakumar, yes sure you can work on the figma design. I'll assign you to the task.

@sivakumarmanoharan you need to fork the repo and comment under that particular issue in order for me to assign you the issue

**Comment by sivakumarmanoharan** [comment] 2024-03-17 22:31
Hi Mehul,

The issue is not resolved yet and still I am facing this issue. Please resolve it so that I can also contribute on it

**Comment by nirogappnith** [comment] 2024-03-19 05:26
> Hi Mehul,
> 
> The issue is not resolved yet and still I am facing this issue. Please resolve it so that I can also contribute on it

DM me your IP address on the slack channel, I'll add your IP
